### PR TITLE
Address blank landing pages

### PR DESCRIPTION
**Pull request by anissa111**
Summary of changes:
- removes `geocat.rst`, `comp.rst`, `viz.rst`, and `uxarray.rst` and merges that content in to `index.rst`
- separates content from deleted repo-specific landing pages' toctrees into multiple top-level toctrees in `index.rst` with captions

### CODE REVIEW

**Comment by anissa111** [comment]
@erogluorhan, with this implementation I suggest removing your second top-level header in `00-Overview.ipynb`, as it's messing with both the left and right navigation bars

toctree screenshot

I didn't want to address that here in case it created more messy merge conflicts.

**Review by erogluorhan — COMMENTED** [review]
This looks good overall, but just to be sure, is it aimed at addressing Issue #3 ?

**Comment by erogluorhan** [comment]
> 

Thanks! Yes, I am addressing that in my `uxarray` branch, which will turn into a PR soon

**Comment by anissa111** [comment]
> This looks good overall, but just to be sure, is it aimed at addressing Issue #3 ?

Haha oops! It was, but now I see I've misinterpreted that issue and that it doesn't actually address #3. 

I thought that issue was about the project-specific landing pages. In retrospect with my new understanding, I'm not actually sure we should be doing the actual issue in #3

**Comment by erogluorhan** [comment]
> 

Okay, let's get this PR merged, and we can discuss Issue #3 after then!

**Review by erogluorhan — APPROVED** [review]

**Pull request merged**
